


services:
  backend:
    build: ./server
    container_name: backend
    restart : always
    env_file: 
      - ./server/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: https://miniature-invention-vx9gj4g6wp4cp7vj-5000.app.github.dev
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
